### ISSUE TITLE
Consider using dry-types over defining your own

### ISSUE THREAD

**Issue by radar** [keygen-sh/typed_params#2]
dry-types may be a more suitable API here, and you could build up more complicated parameter structures using it. It’s also more battle-tested than your library. What do you think about using it here? 

I wrote a post about using dry-types here: https://ryanbigg.com/2022/11/a-replacement-for-strong-parameters

**Comment by ezekg** [comment]
No offense to the maintainers, but I’m not a fan of dry-types (or any of the dry-* gems) simply because it doesn’t feel like “Ruby” to me. I also don’t see any value in replacing any of the internals of `typed_params` with dry-types when everything works as-intended already.
